# Generated by Django 4.0.4 on 2022-04-17 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('team', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='team',
            old_name='member',
            new_name='members',
        ),
    ]
